name: Production release deployment
run-name: ${{ github.actor }} released ${{ github.event.release.tag_name }}
on:
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST -d {} curl -X POST -d {} ${{ secrets.PRODUCTION_DEPLOYMENT_HOOK_URL }}
